version = 5.1.0
archive_dir = /etc/letsencrypt/archive/calnio.com
cert = /etc/letsencrypt/live/calnio.com/cert.pem
privkey = /etc/letsencrypt/live/calnio.com/privkey.pem
chain = /etc/letsencrypt/live/calnio.com/chain.pem
fullchain = /etc/letsencrypt/live/calnio.com/fullchain.pem
[renewalparams]
account = 6f0eeed675ab786848bb64d10ec82c89
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
calnio.com = /var/www/certbot
www.calnio.com = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2025-12-19T09:32:16
