"""add calendar_name to caldav_credentials

Revision ID: 0703ca8b02e9
Revises: ed165f9f9302
Create Date: 2026-08-08 20:28:46.512993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0703ca8b02e9'
down_revision: Union[str, Sequence[str], None] = 'ed165f9f9302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caldav_credentials', sa.Column('calendar_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('caldav_credentials', 'calendar_name')
    # ### end Alembic commands ###
