"""create caldav_credentials table

Revision ID: d379219d19a3
Revises: 673af4d22aca
Create Date: 2026-07-23 20:52:18.172620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd379219d19a3'
down_revision: Union[str, Sequence[str], None] = '673af4d22aca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caldav_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('icloud_email', sa.String(), nullable=False),
    sa.Column('password_encrypted', sa.String(), nullable=False),
    sa.Column('calendar_url', sa.String(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caldav_credentials_user_id'), 'caldav_credentials', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_caldav_credentials_user_id'), table_name='caldav_credentials')
    op.drop_table('caldav_credentials')
    # ### end Alembic commands ###
