"""add title to synced_events

Revision ID: ec5668403e86
Revises: 87509e5f0c39
Create Date: 2026-07-03 22:26:39.073197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec5668403e86'
down_revision: Union[str, Sequence[str], None] = '87509e5f0c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('synced_events', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('synced_events', 'title')
    # ### end Alembic commands ###
