"""rename column

Revision ID: 040918af799d
Revises: b9853889096e
Create Date: 2025-10-24 10:59:02.089686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '040918af799d'
down_revision: Union[str, Sequence[str], None] = 'b9853889096e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notion_tasks', 'caldav_id', new_column_name='caldav_id')
    op.add_column('notion_tasks', sa.Column('sync_status', sa.String(), nullable=False, server_default='pending'))
    op.add_column('caldav_events', sa.Column('sync_status', sa.String(), nullable=False, server_default='pending'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('caldav_events', 'sync_status')
    op.drop_column('notion_tasks', 'sync_status')

    # Rename column back to original
    op.alter_column('notion_tasks', 'caldav_id', new_column_name='caldav_id')
    # ### end Alembic commands ###
