"""change column type

Revision ID: 19fc4fe2811f
Revises: 0dcff28cb147
Create Date: 2025-10-24 11:40:00.275187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19fc4fe2811f'
down_revision: Union[str, Sequence[str], None] = '0dcff28cb147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'notion_tasks',
        'notion_page_id',
        existing_type=sa.String(),
        nullable=True
    )

    # делаем notion_url nullable
    op.alter_column(
        'notion_tasks',
        'notion_url',
        existing_type=sa.String(),
        nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendars',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('external_service', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('calendars_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('calendars_pkey')),
    sa.UniqueConstraint('uid', name=op.f('calendars_uid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('notion_integrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('workspace_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bot_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notion_user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('duplicated_template_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notion_integrations_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notion_integrations_pkey')),
    sa.UniqueConstraint('workspace_id', name=op.f('uq_notion_integrations_workspace_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('notion_tasks',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notion_page_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('notion_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('select_option', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('done', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('sync_source', sa.VARCHAR(), server_default=sa.text("'notion'::character varying"), autoincrement=False, nullable=False),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('caldav_id', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('has_conflict', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('last_modified_source', sa.VARCHAR(), server_default=sa.text("'notion'::character varying"), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('sync_status', postgresql.ENUM('pending', 'done', 'failed', name='syncstatus'), server_default=sa.text("'pending'::syncstatus"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notion_tasks_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notion_tasks_pkey')),
    sa.UniqueConstraint('notion_page_id', name=op.f('notion_tasks_notion_page_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sync_interval_seconds', sa.INTEGER(), server_default=sa.text('300'), autoincrement=False, nullable=False),
    sa.Column('active_sync', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('icloud_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('app_specific_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name='users_username_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('caldav_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('caldav_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notion_page_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notion_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sync_source', sa.VARCHAR(), server_default=sa.text("'caldav'::character varying"), autoincrement=False, nullable=False),
    sa.Column('has_conflict', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('caldav_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sync_status', postgresql.ENUM('pending', 'done', 'failed', name='syncstatus'), server_default=sa.text("'pending'::syncstatus"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_caldav_events_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_caldav_events_pkey')),
    sa.UniqueConstraint('caldav_url', name=op.f('caldav_events_caldav_url_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', 'caldav_id', name=op.f('uq_user_caldav_events_user_caldav_uid'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
