"""add sync_interval_seconds column to users

Revision ID: 424907f7e342
Revises: a3d53bfab21d
Create Date: 2025-09-29 17:19:41.458501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '424907f7e342'
down_revision: Union[str, Sequence[str], None] = 'a3d53bfab21d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sync_interval_seconds', sa.Integer(), nullable=False, server_default="300"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sync_interval_seconds')
    # ### end Alembic commands ###
