"""add new column to users table

Revision ID: 47b95ae4d02f
Revises: 6a3972a46c19
Create Date: 2025-12-17 16:34:37.317868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47b95ae4d02f'
down_revision: Union[str, Sequence[str], None] = '6a3972a46c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sync_interval', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sync_interval')
    # ### end Alembic commands ###
