"""Add unique constraint to workspace_id in notion_integrations

Revision ID: 648e7163d6ae
Revises: f74ea4b9e097
Create Date: 2025-10-03 17:04:02.987994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '648e7163d6ae'
down_revision: Union[str, Sequence[str], None] = 'f74ea4b9e097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_notion_integrations_workspace_id', 'notion_integrations', ['workspace_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_notion_integrations_workspace_id', 'notion_integrations', type_='unique')
    # ### end Alembic commands ###
