"""Added new column

Revision ID: 6a3972a46c19
Revises: 7a35541b1b09
Create Date: 2025-12-16 18:01:33.452519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a3972a46c19'
down_revision: Union[str, Sequence[str], None] = '7a35541b1b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('caldav_calendar_name', sa.String(), nullable=True))

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'caldav_calendar_name')
    # ### end Alembic commands ###
