"""Initial migration

Revision ID: 723eede5975e
Revises: 
Create Date: 2025-09-24 00:37:53.930969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '723eede5975e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notion_tasks', sa.Column('sync_source', sa.String(), nullable=False, server_default='notion'))
    op.add_column('notion_tasks', sa.Column('last_synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('notion_tasks', sa.Column('caldav_uid', sa.String(), nullable=False, server_default=''))
    op.add_column('notion_tasks', sa.Column('has_conflict', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('notion_tasks', sa.Column('last_modified_source', sa.String(), nullable=False, server_default='notion'))
    op.alter_column('notion_tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('notion_tasks', 'notion_page_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('notion_tasks', 'done',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notion_tasks', 'done',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('notion_tasks', 'notion_page_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notion_tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('notion_tasks', 'last_modified_source')
    op.drop_column('notion_tasks', 'has_conflict')
    op.drop_column('notion_tasks', 'caldav_uid')
    op.drop_column('notion_tasks', 'last_synced_at')
    op.drop_column('notion_tasks', 'sync_source')
    # ### end Alembic commands ###
