"""Convert sync_status to PostgreSQL ENUM

Revision ID: a4ab66b804c6
Revises: dc86913f74d2
Create Date: 2025-10-26 23:32:11.968392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4ab66b804c6'
down_revision: Union[str, Sequence[str], None] = 'dc86913f74d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DO $$ BEGIN CREATE TYPE syncstatus AS ENUM ('pending', 'synced', 'failed'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    # Меняем тип колонки
    op.alter_column(
        'caldav_events', 'sync_status',
        type_=sa.Enum('pending', 'synced', 'failed', name='syncstatus'),
        existing_type=sa.VARCHAR(),
        existing_nullable=False
    )

    # Аналогично, если есть другая таблица:
    op.alter_column(
        'notion_tasks', 'sync_status',
        type_=sa.Enum('pending', 'synced', 'failed', name='syncstatus'),
        existing_type=sa.VARCHAR(),
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### end Alembic commands ###
