"""add new collumn

Revision ID: b9853889096e
Revises: fed31d6be9ea
Create Date: 2025-10-22 13:24:34.507945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic.ddl.base import drop_column
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9853889096e'
down_revision: Union[str, Sequence[str], None] = 'fed31d6be9ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caldav_events', sa.Column('caldav_url', sa.String(), unique=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('caldav_events', 'caldav_url')
    # ### end Alembic commands ###
