"""Auto-generated migration

Revision ID: fed31d6be9ea
Revises: d93d7ae96ef5
Create Date: 2025-10-17 12:32:08.175713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fed31d6be9ea'
down_revision: Union[str, Sequence[str], None] = 'd93d7ae96ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user_caldav_events', 'caldav_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('caldav_events', 'user_caldav_events')
    # ### end Alembic commands ###
