# Really basic config
server {
    listen 80;
    server_name calnio.com www.calnio.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        proxy_pass http://calnio:8000;  # или твой backend
    }
}
