version = 5.1.0
archive_dir = /etc/letsencrypt/archive/calnio.com
cert = /etc/letsencrypt/live/calnio.com/cert.pem
privkey = /etc/letsencrypt/live/calnio.com/privkey.pem
chain = /etc/letsencrypt/live/calnio.com/chain.pem
fullchain = /etc/letsencrypt/live/calnio.com/fullchain.pem
[renewalparams]
account = 39f2b092a86c603bdb9112f9045fa875
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
calnio.com = /var/www/certbot
www.calnio.com = /var/www/certbot
