name: Deploy to Digital Ocean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: $ secrets.DO_HOST           # ← Исправлено
          username: $ secrets.DO_USER       # ← Исправлено
          password: $ secrets.DO_PASSWORD   # ← Исправлено
          script: |
            cd /Calnio
            git pull
            git fetch
            docker compose down
            docker compose build --no-cache
            docker compose up -d